FROM python:3.10.2-buster

# run critical system updates ... one could also use the artful-curl pack

RUN apt-get update \
    && apt-get install -y \
    apt-utils \
    build-essential \
    git \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-gnutls-dev \
    libssl-dev \
    libperl-dev \
    libgsl0-dev \
    && apt-get purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoremove -y && \
    rm -rf /var/lib/{apt,dpkg,cache,log}

WORKDIR /opt
RUN git clone --recurse-submodules https://github.com/samtools/htslib.git \
    && cd htslib \
    && make \
    && make install \
    && make clean

WORKDIR /opt
RUN git clone https://github.com/samtools/bcftools.git \
    && cd bcftools \
    && make \
    && make install \
    && make clean

WORKDIR /opt
RUN git clone https://github.com/samtools/samtools.git \
    && cd samtools \
    && autoheader \
    && autoconf -Wno-syntax \
    && ./configure \
    && make \
    && make install \
    && make clean

WORKDIR /
